vm/sysinfo: drop unused includes after ca3794ab13e0
_studio/shared/umc/core/vm/src/vm_sys_info_linux32.c:28:10: fatal error: 'sys/sysinfo.h' file not found
 #include <sys/sysinfo.h>
         ^~~~~~~~~~~~~~~