[build] Some directories are used by hardware encoder as well
In file included from _studio/mfx_lib/encode/mjpeg/src/mfx_mjpeg_encode.cpp:29:
_studio/mfx_lib/encode/mjpeg/include/mfx_mjpeg_encode.h:32:10: fatal error: 'umc_mjpeg_video_encoder.h' file not found
 #include "umc_mjpeg_video_encoder.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~