Fix build error introduced by clang-14
Clang-14 complains about an unusual way of converting
a pointer to an integer:

error: invalid operands to binary expression
('uintptr_t *' (aka 'unsigned long *') and 'unsigned long')
   return (T) ((((uintptr_t *) pv) + (lAlignValue - 1)) &

Replace this with a normal cast to uintptr_t.

Tracked-On: OAM-103588
Signed-off-by: svenate <salini.venate@intel.com>